### ISSUE TITLE
not matched keys

### ISSUE THREAD

**Issue by ceylani** [CpanelInc/cplocales#12]
Some keys (1240 keys) in en.yaml files but they are not in tr.yaml. 

For example: 14789th line in en.yaml  "“[_1]” is suspended.": ''  is not in tr.yaml file. 
or 15328th line in tr.yaml "← Go Back to Interface Elements": '← Arabirim Unsurlarına Geri Dön' is not in en.yaml.

**Comment by bk2204** [comment]
There are two reasons for this.

First, if a string is in en.yaml but not another file, then it hasn't been translated for that locale.  That can happen because of a delay between harvesting the string (adding it for translation) and getting the translation back.  I expect to see a new set of translations submitted as a pull request some time in the next couple days.

If a string is in a non-English file but not in the English file, that's usually because we used to have it in the product and we translated it, but it has been removed (usually because it was superseded by a different string).  We certainly can remove those, but they could still be useful for people using older versions of cPanel & WHM. They don't really harm anything other than making the locale databases slightly larger.

**Comment by ceylani** [comment]
I'll append not matched strings to end of tr.yaml file, right?

**Comment by ceylani** [comment]
I can synchronize both files fully. Shall I do that?

**Comment by bk2204** [comment]
While I look into things more carefully, I'd recommend just appending the missing en.yaml strings to tr.yaml if you're going to translate them.  Leaving the ones you're not going to translate out is helpful because it makes it very easy to determine which strings haven't been translated.

**Comment by ceylani** [comment]
thanks,
